export const PRIMARY_BLACK_COLOR = '#246bfd';
export const PRIMARY_BLACK_TEXT_COLOR = '#FFF';
export const SECONDARY_BLACK_TEXT_COLOR = '#000';
export const PRIMARY_BLACK_BACKGROUND_COLOR = '#181a20';
export const SECONDARY_BLACK_BACKGROUND_COLOR = '#262a34';

export const PRIMARY_LIGHT_COLOR = '#246bfd';
export const PRIMARY_LIGHT_TEXT_COLOR = '#000';
export const SECONDARY_LIGHT_TEXT_COLOR = '#FFF';
export const PRIMARY_LIGHT_BACKGROUND_COLOR = '#FFFFFF';
export const SECONDARY_LIGHT_BACKGROUND_COLOR = '#F2F2F2';
